apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: docker.io/ganeshkhaire14/node-backend
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: flask
spec:
  selector:
    app: flask-backend
  ports:
  - port: 5000
    targetPort: 5000
