version: '3.8'

services:
  backend:
    build: ./backend
    hostname: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge

