apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
        - name: flask-frontend
          image: docker.io/ganeshkhaire14/node-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend
spec:
  selector:
    app: flask-frontend
  ports:
  - port: 3000
    targetPort: 3000